tasks:
  - command: echo "Welcome to Gitpod environment with AWS CLI v2! You have to configure using 'aws configure' command first." ; complete -C aws_completer aws; aws configure
    
image:
  file: .gitpod.Dockerfile

